services:
  ws-client:
    build:
      context: ..
      dockerfile: client/Dockerfile
    image: ws-client
    deploy:
      replicas: 1
    network_mode: "bridge"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["/app/client", "-ip=host.docker.internal", "-n=100", "-mode=grpc"]
# "-conn=100", "-ip=9.141.20.46"
    
