// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: tracking/v1/tracking.proto

package trackingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DriverLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Lat           *float64               `protobuf:"fixed64,2,opt,name=lat,proto3,oneof" json:"lat,omitempty"`
	Lng           *float64               `protobuf:"fixed64,3,opt,name=lng,proto3,oneof" json:"lng,omitempty"`
	CompanyId     string                 `protobuf:"bytes,4,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverLocation) Reset() {
	*x = DriverLocation{}
	mi := &file_tracking_v1_tracking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverLocation) ProtoMessage() {}

func (x *DriverLocation) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v1_tracking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverLocation.ProtoReflect.Descriptor instead.
func (*DriverLocation) Descriptor() ([]byte, []int) {
	return file_tracking_v1_tracking_proto_rawDescGZIP(), []int{0}
}

func (x *DriverLocation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DriverLocation) GetLat() float64 {
	if x != nil && x.Lat != nil {
		return *x.Lat
	}
	return 0
}

func (x *DriverLocation) GetLng() float64 {
	if x != nil && x.Lng != nil {
		return *x.Lng
	}
	return 0
}

func (x *DriverLocation) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type PublishAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishAck) Reset() {
	*x = PublishAck{}
	mi := &file_tracking_v1_tracking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishAck) ProtoMessage() {}

func (x *PublishAck) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v1_tracking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishAck.ProtoReflect.Descriptor instead.
func (*PublishAck) Descriptor() ([]byte, []int) {
	return file_tracking_v1_tracking_proto_rawDescGZIP(), []int{1}
}

func (x *PublishAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TrackDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackDriverRequest) Reset() {
	*x = TrackDriverRequest{}
	mi := &file_tracking_v1_tracking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackDriverRequest) ProtoMessage() {}

func (x *TrackDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v1_tracking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackDriverRequest.ProtoReflect.Descriptor instead.
func (*TrackDriverRequest) Descriptor() ([]byte, []int) {
	return file_tracking_v1_tracking_proto_rawDescGZIP(), []int{2}
}

func (x *TrackDriverRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type GetDriversRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriversRequest) Reset() {
	*x = GetDriversRequest{}
	mi := &file_tracking_v1_tracking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriversRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriversRequest) ProtoMessage() {}

func (x *GetDriversRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v1_tracking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriversRequest.ProtoReflect.Descriptor instead.
func (*GetDriversRequest) Descriptor() ([]byte, []int) {
	return file_tracking_v1_tracking_proto_rawDescGZIP(), []int{3}
}

func (x *GetDriversRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetBBoxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinLat        float64                `protobuf:"fixed64,1,opt,name=min_lat,json=minLat,proto3" json:"min_lat,omitempty"`
	MinLng        float64                `protobuf:"fixed64,2,opt,name=min_lng,json=minLng,proto3" json:"min_lng,omitempty"`
	MaxLat        float64                `protobuf:"fixed64,3,opt,name=max_lat,json=maxLat,proto3" json:"max_lat,omitempty"`
	MaxLng        float64                `protobuf:"fixed64,4,opt,name=max_lng,json=maxLng,proto3" json:"max_lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBBoxRequest) Reset() {
	*x = GetBBoxRequest{}
	mi := &file_tracking_v1_tracking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBBoxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBBoxRequest) ProtoMessage() {}

func (x *GetBBoxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v1_tracking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBBoxRequest.ProtoReflect.Descriptor instead.
func (*GetBBoxRequest) Descriptor() ([]byte, []int) {
	return file_tracking_v1_tracking_proto_rawDescGZIP(), []int{4}
}

func (x *GetBBoxRequest) GetMinLat() float64 {
	if x != nil {
		return x.MinLat
	}
	return 0
}

func (x *GetBBoxRequest) GetMinLng() float64 {
	if x != nil {
		return x.MinLng
	}
	return 0
}

func (x *GetBBoxRequest) GetMaxLat() float64 {
	if x != nil {
		return x.MaxLat
	}
	return 0
}

func (x *GetBBoxRequest) GetMaxLng() float64 {
	if x != nil {
		return x.MaxLng
	}
	return 0
}

type Driver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,3,opt,name=lng,proto3" json:"lng,omitempty"`
	From          string                 `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	Session       string                 `protobuf:"bytes,5,opt,name=session,proto3" json:"session,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastSeen      string                 `protobuf:"bytes,8,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Active        bool                   `protobuf:"varint,9,opt,name=active,proto3" json:"active,omitempty"`
	CompanyId     string                 `protobuf:"bytes,10,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	DriverType    int32                  `protobuf:"varint,11,opt,name=driver_type,json=driverType,proto3" json:"driver_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Driver) Reset() {
	*x = Driver{}
	mi := &file_tracking_v1_tracking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Driver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Driver) ProtoMessage() {}

func (x *Driver) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v1_tracking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Driver.ProtoReflect.Descriptor instead.
func (*Driver) Descriptor() ([]byte, []int) {
	return file_tracking_v1_tracking_proto_rawDescGZIP(), []int{5}
}

func (x *Driver) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Driver) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Driver) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *Driver) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Driver) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *Driver) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Driver) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Driver) GetLastSeen() string {
	if x != nil {
		return x.LastSeen
	}
	return ""
}

func (x *Driver) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Driver) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *Driver) GetDriverType() int32 {
	if x != nil {
		return x.DriverType
	}
	return 0
}

type DriverLocationUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,3,opt,name=lng,proto3" json:"lng,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CompanyId     string                 `protobuf:"bytes,5,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	UnixTime      string                 `protobuf:"bytes,6,opt,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverLocationUpdate) Reset() {
	*x = DriverLocationUpdate{}
	mi := &file_tracking_v1_tracking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverLocationUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverLocationUpdate) ProtoMessage() {}

func (x *DriverLocationUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v1_tracking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverLocationUpdate.ProtoReflect.Descriptor instead.
func (*DriverLocationUpdate) Descriptor() ([]byte, []int) {
	return file_tracking_v1_tracking_proto_rawDescGZIP(), []int{6}
}

func (x *DriverLocationUpdate) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *DriverLocationUpdate) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *DriverLocationUpdate) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *DriverLocationUpdate) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *DriverLocationUpdate) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *DriverLocationUpdate) GetUnixTime() string {
	if x != nil {
		return x.UnixTime
	}
	return ""
}

type DriversResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Drivers       []*Driver              `protobuf:"bytes,2,rep,name=drivers,proto3" json:"drivers,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriversResponse) Reset() {
	*x = DriversResponse{}
	mi := &file_tracking_v1_tracking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriversResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriversResponse) ProtoMessage() {}

func (x *DriversResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v1_tracking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriversResponse.ProtoReflect.Descriptor instead.
func (*DriversResponse) Descriptor() ([]byte, []int) {
	return file_tracking_v1_tracking_proto_rawDescGZIP(), []int{7}
}

func (x *DriversResponse) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *DriversResponse) GetDrivers() []*Driver {
	if x != nil {
		return x.Drivers
	}
	return nil
}

func (x *DriversResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type WatcherEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Drivers       []*Driver              `protobuf:"bytes,2,rep,name=drivers,proto3" json:"drivers,omitempty"`
	DriverData    *DriverLocationUpdate  `protobuf:"bytes,3,opt,name=driver_data,json=driverData,proto3" json:"driver_data,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatcherEvent) Reset() {
	*x = WatcherEvent{}
	mi := &file_tracking_v1_tracking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatcherEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatcherEvent) ProtoMessage() {}

func (x *WatcherEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v1_tracking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatcherEvent.ProtoReflect.Descriptor instead.
func (*WatcherEvent) Descriptor() ([]byte, []int) {
	return file_tracking_v1_tracking_proto_rawDescGZIP(), []int{8}
}

func (x *WatcherEvent) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *WatcherEvent) GetDrivers() []*Driver {
	if x != nil {
		return x.Drivers
	}
	return nil
}

func (x *WatcherEvent) GetDriverData() *DriverLocationUpdate {
	if x != nil {
		return x.DriverData
	}
	return nil
}

func (x *WatcherEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *WatcherEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_tracking_v1_tracking_proto protoreflect.FileDescriptor

const file_tracking_v1_tracking_proto_rawDesc = "" +
	"\n" +
	"\x1atracking/v1/tracking.proto\x12\vtracking.v1\"}\n" +
	"\x0eDriverLocation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x03lat\x18\x02 \x01(\x01H\x00R\x03lat\x88\x01\x01\x12\x15\n" +
	"\x03lng\x18\x03 \x01(\x01H\x01R\x03lng\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"company_id\x18\x04 \x01(\tR\tcompanyIdB\x06\n" +
	"\x04_latB\x06\n" +
	"\x04_lng\"$\n" +
	"\n" +
	"PublishAck\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"1\n" +
	"\x12TrackDriverRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\"'\n" +
	"\x11GetDriversRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\"t\n" +
	"\x0eGetBBoxRequest\x12\x17\n" +
	"\amin_lat\x18\x01 \x01(\x01R\x06minLat\x12\x17\n" +
	"\amin_lng\x18\x02 \x01(\x01R\x06minLng\x12\x17\n" +
	"\amax_lat\x18\x03 \x01(\x01R\x06maxLat\x12\x17\n" +
	"\amax_lng\x18\x04 \x01(\x01R\x06maxLng\"\x9d\x02\n" +
	"\x06Driver\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x03 \x01(\x01R\x03lng\x12\x12\n" +
	"\x04from\x18\x04 \x01(\tR\x04from\x12\x18\n" +
	"\asession\x18\x05 \x01(\tR\asession\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\x1b\n" +
	"\tlast_seen\x18\b \x01(\tR\blastSeen\x12\x16\n" +
	"\x06active\x18\t \x01(\bR\x06active\x12\x1d\n" +
	"\n" +
	"company_id\x18\n" +
	" \x01(\tR\tcompanyId\x12\x1f\n" +
	"\vdriver_type\x18\v \x01(\x05R\n" +
	"driverType\"\xb1\x01\n" +
	"\x14DriverLocationUpdate\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x03 \x01(\x01R\x03lng\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x1d\n" +
	"\n" +
	"company_id\x18\x05 \x01(\tR\tcompanyId\x12\x1b\n" +
	"\tunix_time\x18\x06 \x01(\tR\bunixTime\"p\n" +
	"\x0fDriversResponse\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12-\n" +
	"\adrivers\x18\x02 \x03(\v2\x13.tracking.v1.DriverR\adrivers\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"\xc9\x01\n" +
	"\fWatcherEvent\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12-\n" +
	"\adrivers\x18\x02 \x03(\v2\x13.tracking.v1.DriverR\adrivers\x12B\n" +
	"\vdriver_data\x18\x03 \x01(\v2!.tracking.v1.DriverLocationUpdateR\n" +
	"driverData\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status2\x88\x03\n" +
	"\rDriverTracker\x12G\n" +
	"\x0fPublishLocation\x12\x1b.tracking.v1.DriverLocation\x1a\x17.tracking.v1.PublishAck\x12O\n" +
	"\x15PublishLocationStream\x12\x1b.tracking.v1.DriverLocation\x1a\x17.tracking.v1.PublishAck(\x01\x12K\n" +
	"\vTrackDriver\x12\x1f.tracking.v1.TrackDriverRequest\x1a\x19.tracking.v1.WatcherEvent0\x01\x12J\n" +
	"\n" +
	"GetDrivers\x12\x1e.tracking.v1.GetDriversRequest\x1a\x1c.tracking.v1.DriversResponse\x12D\n" +
	"\aGetBBox\x12\x1b.tracking.v1.GetBBoxRequest\x1a\x1c.tracking.v1.DriversResponseB'Z%fastsocket/grpc/trackingpb;trackingpbb\x06proto3"

var (
	file_tracking_v1_tracking_proto_rawDescOnce sync.Once
	file_tracking_v1_tracking_proto_rawDescData []byte
)

func file_tracking_v1_tracking_proto_rawDescGZIP() []byte {
	file_tracking_v1_tracking_proto_rawDescOnce.Do(func() {
		file_tracking_v1_tracking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tracking_v1_tracking_proto_rawDesc), len(file_tracking_v1_tracking_proto_rawDesc)))
	})
	return file_tracking_v1_tracking_proto_rawDescData
}

var file_tracking_v1_tracking_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_tracking_v1_tracking_proto_goTypes = []any{
	(*DriverLocation)(nil),       // 0: tracking.v1.DriverLocation
	(*PublishAck)(nil),           // 1: tracking.v1.PublishAck
	(*TrackDriverRequest)(nil),   // 2: tracking.v1.TrackDriverRequest
	(*GetDriversRequest)(nil),    // 3: tracking.v1.GetDriversRequest
	(*GetBBoxRequest)(nil),       // 4: tracking.v1.GetBBoxRequest
	(*Driver)(nil),               // 5: tracking.v1.Driver
	(*DriverLocationUpdate)(nil), // 6: tracking.v1.DriverLocationUpdate
	(*DriversResponse)(nil),      // 7: tracking.v1.DriversResponse
	(*WatcherEvent)(nil),         // 8: tracking.v1.WatcherEvent
}
var file_tracking_v1_tracking_proto_depIdxs = []int32{
	5, // 0: tracking.v1.DriversResponse.drivers:type_name -> tracking.v1.Driver
	5, // 1: tracking.v1.WatcherEvent.drivers:type_name -> tracking.v1.Driver
	6, // 2: tracking.v1.WatcherEvent.driver_data:type_name -> tracking.v1.DriverLocationUpdate
	0, // 3: tracking.v1.DriverTracker.PublishLocation:input_type -> tracking.v1.DriverLocation
	0, // 4: tracking.v1.DriverTracker.PublishLocationStream:input_type -> tracking.v1.DriverLocation
	2, // 5: tracking.v1.DriverTracker.TrackDriver:input_type -> tracking.v1.TrackDriverRequest
	3, // 6: tracking.v1.DriverTracker.GetDrivers:input_type -> tracking.v1.GetDriversRequest
	4, // 7: tracking.v1.DriverTracker.GetBBox:input_type -> tracking.v1.GetBBoxRequest
	1, // 8: tracking.v1.DriverTracker.PublishLocation:output_type -> tracking.v1.PublishAck
	1, // 9: tracking.v1.DriverTracker.PublishLocationStream:output_type -> tracking.v1.PublishAck
	8, // 10: tracking.v1.DriverTracker.TrackDriver:output_type -> tracking.v1.WatcherEvent
	7, // 11: tracking.v1.DriverTracker.GetDrivers:output_type -> tracking.v1.DriversResponse
	7, // 12: tracking.v1.DriverTracker.GetBBox:output_type -> tracking.v1.DriversResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_tracking_v1_tracking_proto_init() }
func file_tracking_v1_tracking_proto_init() {
	if File_tracking_v1_tracking_proto != nil {
		return
	}
	file_tracking_v1_tracking_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tracking_v1_tracking_proto_rawDesc), len(file_tracking_v1_tracking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tracking_v1_tracking_proto_goTypes,
		DependencyIndexes: file_tracking_v1_tracking_proto_depIdxs,
		MessageInfos:      file_tracking_v1_tracking_proto_msgTypes,
	}.Build()
	File_tracking_v1_tracking_proto = out.File
	file_tracking_v1_tracking_proto_goTypes = nil
	file_tracking_v1_tracking_proto_depIdxs = nil
}
