// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: tracking/v1/tracking.proto

package trackingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DriverTracker_PublishLocation_FullMethodName       = "/tracking.v1.DriverTracker/PublishLocation"
	DriverTracker_PublishLocationStream_FullMethodName = "/tracking.v1.DriverTracker/PublishLocationStream"
	DriverTracker_TrackDriver_FullMethodName           = "/tracking.v1.DriverTracker/TrackDriver"
	DriverTracker_GetDrivers_FullMethodName            = "/tracking.v1.DriverTracker/GetDrivers"
	DriverTracker_GetBBox_FullMethodName               = "/tracking.v1.DriverTracker/GetBBox"
)

// DriverTrackerClient is the client API for DriverTracker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DriverTrackerClient interface {
	PublishLocation(ctx context.Context, in *DriverLocation, opts ...grpc.CallOption) (*PublishAck, error)
	PublishLocationStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DriverLocation, PublishAck], error)
	TrackDriver(ctx context.Context, in *TrackDriverRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatcherEvent], error)
	GetDrivers(ctx context.Context, in *GetDriversRequest, opts ...grpc.CallOption) (*DriversResponse, error)
	GetBBox(ctx context.Context, in *GetBBoxRequest, opts ...grpc.CallOption) (*DriversResponse, error)
}

type driverTrackerClient struct {
	cc grpc.ClientConnInterface
}

func NewDriverTrackerClient(cc grpc.ClientConnInterface) DriverTrackerClient {
	return &driverTrackerClient{cc}
}

func (c *driverTrackerClient) PublishLocation(ctx context.Context, in *DriverLocation, opts ...grpc.CallOption) (*PublishAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishAck)
	err := c.cc.Invoke(ctx, DriverTracker_PublishLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverTrackerClient) PublishLocationStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DriverLocation, PublishAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DriverTracker_ServiceDesc.Streams[0], DriverTracker_PublishLocationStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DriverLocation, PublishAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DriverTracker_PublishLocationStreamClient = grpc.ClientStreamingClient[DriverLocation, PublishAck]

func (c *driverTrackerClient) TrackDriver(ctx context.Context, in *TrackDriverRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatcherEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DriverTracker_ServiceDesc.Streams[1], DriverTracker_TrackDriver_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TrackDriverRequest, WatcherEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DriverTracker_TrackDriverClient = grpc.ServerStreamingClient[WatcherEvent]

func (c *driverTrackerClient) GetDrivers(ctx context.Context, in *GetDriversRequest, opts ...grpc.CallOption) (*DriversResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriversResponse)
	err := c.cc.Invoke(ctx, DriverTracker_GetDrivers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverTrackerClient) GetBBox(ctx context.Context, in *GetBBoxRequest, opts ...grpc.CallOption) (*DriversResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriversResponse)
	err := c.cc.Invoke(ctx, DriverTracker_GetBBox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriverTrackerServer is the server API for DriverTracker service.
// All implementations must embed UnimplementedDriverTrackerServer
// for forward compatibility.
type DriverTrackerServer interface {
	PublishLocation(context.Context, *DriverLocation) (*PublishAck, error)
	PublishLocationStream(grpc.ClientStreamingServer[DriverLocation, PublishAck]) error
	TrackDriver(*TrackDriverRequest, grpc.ServerStreamingServer[WatcherEvent]) error
	GetDrivers(context.Context, *GetDriversRequest) (*DriversResponse, error)
	GetBBox(context.Context, *GetBBoxRequest) (*DriversResponse, error)
	mustEmbedUnimplementedDriverTrackerServer()
}

// UnimplementedDriverTrackerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDriverTrackerServer struct{}

func (UnimplementedDriverTrackerServer) PublishLocation(context.Context, *DriverLocation) (*PublishAck, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishLocation not implemented")
}
func (UnimplementedDriverTrackerServer) PublishLocationStream(grpc.ClientStreamingServer[DriverLocation, PublishAck]) error {
	return status.Error(codes.Unimplemented, "method PublishLocationStream not implemented")
}
func (UnimplementedDriverTrackerServer) TrackDriver(*TrackDriverRequest, grpc.ServerStreamingServer[WatcherEvent]) error {
	return status.Error(codes.Unimplemented, "method TrackDriver not implemented")
}
func (UnimplementedDriverTrackerServer) GetDrivers(context.Context, *GetDriversRequest) (*DriversResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDrivers not implemented")
}
func (UnimplementedDriverTrackerServer) GetBBox(context.Context, *GetBBoxRequest) (*DriversResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBBox not implemented")
}
func (UnimplementedDriverTrackerServer) mustEmbedUnimplementedDriverTrackerServer() {}
func (UnimplementedDriverTrackerServer) testEmbeddedByValue()                       {}

// UnsafeDriverTrackerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriverTrackerServer will
// result in compilation errors.
type UnsafeDriverTrackerServer interface {
	mustEmbedUnimplementedDriverTrackerServer()
}

func RegisterDriverTrackerServer(s grpc.ServiceRegistrar, srv DriverTrackerServer) {
	// If the following call panics, it indicates UnimplementedDriverTrackerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DriverTracker_ServiceDesc, srv)
}

func _DriverTracker_PublishLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverLocation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverTrackerServer).PublishLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverTracker_PublishLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverTrackerServer).PublishLocation(ctx, req.(*DriverLocation))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverTracker_PublishLocationStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DriverTrackerServer).PublishLocationStream(&grpc.GenericServerStream[DriverLocation, PublishAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DriverTracker_PublishLocationStreamServer = grpc.ClientStreamingServer[DriverLocation, PublishAck]

func _DriverTracker_TrackDriver_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TrackDriverRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DriverTrackerServer).TrackDriver(m, &grpc.GenericServerStream[TrackDriverRequest, WatcherEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DriverTracker_TrackDriverServer = grpc.ServerStreamingServer[WatcherEvent]

func _DriverTracker_GetDrivers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriversRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverTrackerServer).GetDrivers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverTracker_GetDrivers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverTrackerServer).GetDrivers(ctx, req.(*GetDriversRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverTracker_GetBBox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBBoxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverTrackerServer).GetBBox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverTracker_GetBBox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverTrackerServer).GetBBox(ctx, req.(*GetBBoxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DriverTracker_ServiceDesc is the grpc.ServiceDesc for DriverTracker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DriverTracker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tracking.v1.DriverTracker",
	HandlerType: (*DriverTrackerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishLocation",
			Handler:    _DriverTracker_PublishLocation_Handler,
		},
		{
			MethodName: "GetDrivers",
			Handler:    _DriverTracker_GetDrivers_Handler,
		},
		{
			MethodName: "GetBBox",
			Handler:    _DriverTracker_GetBBox_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PublishLocationStream",
			Handler:       _DriverTracker_PublishLocationStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "TrackDriver",
			Handler:       _DriverTracker_TrackDriver_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tracking/v1/tracking.proto",
}
